// Generated by scripts/sync-shared.mjs from src/ — do not edit here.
export const TEXTS: Record<string, Record<string, string>> = {
  "pt-PT": {
    "start": "{{task}} começa agora.",
    "overtime": "O tempo previsto para {{task}} terminou. Continuas, ou paras um momento para decidir?",
    "leave": "Para chegares a horas a {{item}}, está na hora de sair.",
    "deadlineEve": "O prazo de {{task}} é amanhã.",
    "deadlineDay": "O prazo de {{task}} é hoje.",
    "dateIn": "{{date}} é daqui a {{n}} dias.",
    "dateTomorrow": "{{date}} é amanhã.",
    "dateToday": "{{date}} é hoje.",
    "planTomorrow": "Antes de terminares o dia: o que é que amanhã tem mesmo de acontecer?",
    "weeklyReview": "A semana fechou. Dez minutos para perceberes o que ela te ensinou?",
    "decisionReview": "Há {{n}} dias decidiste: {{decision}}. Como correu?",
    "eventOutcome": "Como correu {{event}}?",
    "sessionStill": "Ainda estás em {{activity}}?",
    "sessionWhat": "O que estás a fazer agora?",
    "goodMorning": "Bom dia. Hoje tens {{n}} tarefas e {{m}} compromissos.",
    "rested": "Enquanto descansavas: {{n}} lembretes à tua espera.",
    "test": "As notificações da MarTime estão a funcionar.",
    "goalReview": "Está na hora de rever {{goal}}."
  },
  "en": {
    "start": "{{task}} starts now.",
    "overtime": "The planned time for {{task}} is up. Keep going, or pause to decide?",
    "leave": "To arrive on time for {{item}}, it's time to leave.",
    "deadlineEve": "{{task}} is due tomorrow.",
    "deadlineDay": "{{task}} is due today.",
    "dateIn": "{{date}} is in {{n}} days.",
    "dateTomorrow": "{{date}} is tomorrow.",
    "dateToday": "{{date}} is today.",
    "planTomorrow": "Before you end the day: what really has to happen tomorrow?",
    "weeklyReview": "The week is done. Ten minutes to see what it taught you?",
    "decisionReview": "{{n}} days ago you decided: {{decision}}. How did it go?",
    "eventOutcome": "How did {{event}} go?",
    "sessionStill": "Still on {{activity}}?",
    "sessionWhat": "What are you doing now?",
    "goodMorning": "Good morning. Today you have {{n}} tasks and {{m}} events.",
    "rested": "While you rested: {{n}} reminders waiting.",
    "test": "MarTime notifications are working.",
    "goalReview": "Time to review {{goal}}."
  }
};
