// Copies the dependency-free time and silence rules (and the notification texts) into the Edge Functions.
import { readFileSync, writeFileSync } from 'node:fs';

const out = 'supabase/functions/_shared/';
const banner = '// Generated by scripts/sync-shared.mjs from src/ — do not edit here.\n';
writeFileSync(out + 'time.ts', banner + readFileSync('src/lib/time.ts', 'utf8'));
writeFileSync(out + 'silence.ts', banner + readFileSync('src/lib/domain/silence.ts', 'utf8').replace("from '../time'", "from './time.ts'"));
const pt = JSON.parse(readFileSync('src/i18n/pt-PT.json', 'utf8')).notifText;
const en = JSON.parse(readFileSync('src/i18n/en.json', 'utf8')).notifText;
writeFileSync(out + 'texts.ts', banner + `export const TEXTS: Record<string, Record<string, string>> = ${JSON.stringify({ 'pt-PT': pt, en }, null, 2)};\n`);
console.log('shared files written');
